version: '3.9'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: '${COMPOSE_PROJECT_NAME}-client-${APPVERSION}'
    ports:
     # Host port:Container port
      - '3000:3000'
    stdin_open: true
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: '${COMPOSE_PROJECT_NAME}-server-${APPVERSION}'
    ports:
       # Host port:Container port
      - '4000:4000'
    volumes:
      # Bind-mounts configuration
      - ./server:/app      
